server:
  port: 8081

spring:
  application:
    name: covoiturage-digitalise-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/covoiturage_digitalise
    username: postgres
    password: lifegood123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

jwt:
  secret: CovoiturageDigitaliseSecretKey2024VeryLongKey
  expiration: 86400000 # 24h

logging:
  level:
    com.covoituragedigitalise: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html